import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen relative">
          <h1 className="absolute top-0 w-full text-center p-[.5vw] font-semibold bg-white shadow-md max-sm:text-xl sm:text-[2vw] text-slate-700">
            Clip Share
          </h1>
          <div className="bg-cyan-50  w-full h-[100%] flex justify-center items-center flex-col gap-[1vw]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
